### PR TITLE
Integrate Ada Lua into the Alire ecosystem

### PR DESCRIPTION
**Pull request by Patschkowski**
I would like to merge the following to make this library available as an Alire crate. I can also "alr publish" from my own repo but I think it makes more sense if this original repo from AdaCore is used for this purpose.

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Thank you @Patschkowski, we will have a look at the patch.

One problem I see so far is that we don't have any tagged releases of `ada-lua` to make an Alire crate from.

**Comment by Patschkowski** [comment]
@Fabien-Chouteau 
I think you not necessarily need a tagged release. As far as I understand any commit (identified by its hash) is good enough to make an Alire crate. But I am happy to learn otherwise.

**Comment by Fabien-Chouteau** [comment]
This is doable in Alire but it is not compatible with our procedures. I will see what we can do.

**Comment by Patschkowski** [comment]
@Fabien-Chouteau Great, I will make a GNAT Tracker ticket from this :)

**Comment by Fabien-Chouteau** [comment]
Hello @Patschkowski,

ada-lua is now available in Alire: https://alire.ada.dev/crates/ada_lua

Please open a separate pull-request for the style issue correction of this PR.

Regards,

**Pull request closed without merging**
